import org.ihtsdo.drools.domain.Concept
import org.ihtsdo.drools.domain.Relationship
import org.ihtsdo.drools.domain.Constants
import org.ihtsdo.drools.response.InvalidContent
import java.util.ArrayList

global java.util.List invalidContent

rule "An active concept must not have two or more axioms containing only 'is a' relationships."
	dialect "mvel"
	when
		c : Concept(active)
		r1 : Relationship(active, typeId == Constants.IS_A, characteristicTypeId == Constants.STATED_RELATIONSHIP, !axiomGCI)
		activeStatedRelationship1: ArrayList( size == 1 )
				from collect( Relationship(active, !axiomGCI, sourceId == c.id, axiomId == r1.axiomId, characteristicTypeId == Constants.STATED_RELATIONSHIP))
		r2 : Relationship(active, id != r1.id, axiomId != r1.axiomId, typeId == Constants.IS_A, characteristicTypeId == Constants.STATED_RELATIONSHIP, !axiomGCI)
		activeStatedRelationship2: ArrayList( size == 1 )
				from collect( Relationship(active, !axiomGCI, sourceId == c.id, axiomId == r2.axiomId, characteristicTypeId == Constants.STATED_RELATIONSHIP))
	then
		InvalidContent invalid = new InvalidContent("e77f303a-a954-477b-b73b-b05516cf3fc7",
				c, "An active concept must not have two or more axioms containing only 'is a' relationships.");
		invalid.ignorePublishedCheck()
		invalidContent.add(invalid);
end
