import org.ihtsdo.drools.domain.Description
import org.ihtsdo.drools.response.InvalidContent

global java.util.List invalidContent

rule "Term double, leading or trailing spaces"
    dialect "mvel"
    when
        d : Description(term matches ".*  .*" || term matches " .*" || term matches ".* ")
    then
        invalidContent.add(new org.ihtsdo.drools.response.InvalidContent(d, "The system has detected a contradiction of the following convention: Term must not contain double, leading or trailing spaces."));
end

rule "Active descriptions do not have spaces, either before or after, hyphens."
    dialect "mvel"
    when
        d : Description(active && (term matches ".* -.*" || term matches ".*- .*"))
    then
        invalidContent.add(new org.ihtsdo.drools.response.InvalidContent(d, "The system has detected a contradiction of the following convention: active descriptions must not have spaces, either before or after, hyphens."));
end
