import org.ihtsdo.drools.domain.Constants
import org.ihtsdo.drools.domain.Relationship
import org.ihtsdo.drools.service.ConceptService
import org.ihtsdo.drools.response.InvalidContent

global java.util.List invalidContent
global ConceptService conceptService

rule "A concept can not have inactive ancestors"
	dialect "mvel"
	when
		r : Relationship(active && typeId == Constants.IS_A && !conceptService.isActive(destinationId))
	then
		invalidContent.add(new InvalidContent("6784af0e-5ff0-4d3e-b3e3-9c2866a4f0d9",
				r, "A concept must not be the descendant of an inactive concept."));
end
