import org.ihtsdo.drools.domain.Description
import org.ihtsdo.drools.domain.Constants
import org.ihtsdo.drools.response.InvalidContent
import org.ihtsdo.drools.response.Severity

global java.util.List invalidContent

rule "Irish Extension: Text definitions should be case-sensitive."
	dialect "mvel"
	when
		d : Description(active && textDefinition && caseSignificanceId != Constants.ENTIRE_TERM_CASE_SENSITIVE)
	then
		invalidContent.add(new InvalidContent("56ddd9c0-3479-4033-9727-ebc135b2f6ec",
				d, "Text definitions should be case-sensitive.", Severity.WARNING));
end
