import org.ihtsdo.drools.domain.Description
import org.ihtsdo.drools.domain.Concept
import org.ihtsdo.drools.response.InvalidContent
import org.ihtsdo.drools.response.Severity

global java.util.List invalidContent

rule "Term double, leading or trailing spaces"
	dialect "mvel"
	when
		c : Concept(active)
		d : Description(active && term matches ".*  .*" || term matches " .*" || term matches ".* ")
	then
		invalidContent.add(new InvalidContent(d, "Terms must not contain double, leading or trailing spaces."));
end

rule "Active descriptions do not have spaces, either before or after, hyphens."
	dialect "mvel"
	when
		d : Description(active && moduleId != "554471000005108" /*Danish module*/ && (term matches ".* -.*" || term matches ".*- .*"))
	then
		invalidContent.add(new InvalidContent(d, "Active descriptions should not have spaces, either before or after, hyphens.", Severity.WARNING));
end
