import org.ihtsdo.drools.domain.Concept
import org.ihtsdo.drools.domain.Description
import org.ihtsdo.drools.helper.DescriptionHelper
import org.ihtsdo.drools.service.DescriptionService
import org.ihtsdo.drools.response.InvalidContent

global java.util.List invalidContent
global DescriptionService descriptionService

rule "Active term unique in hierarchy"
    dialect "mvel"
    when
    	c : Concept(active)
    	d : Description(active)
    	$duplicate : Description(active && id != d.id) from descriptionService.findMatchingDescriptionInHierarchy(c, d)
    then
        invalidContent.add(new InvalidContent(d, "The system has detected a contradiction of the following convention: active term already exists within this hierarchy on concept " + $duplicate.conceptId +
         "Two active descriptions in the same hierarchy may have the same term only if they have different language codes"));
end
