import org.ihtsdo.drools.domain.Concept
import org.ihtsdo.drools.domain.Description
import org.ihtsdo.drools.domain.Constants
import java.util.Collection
import java.util.ArrayList
import org.ihtsdo.drools.helper.DescriptionHelper
import org.ihtsdo.drools.response.InvalidContent
import org.ihtsdo.drools.helper.ConceptHelper

global java.util.List invalidContent

rule "New Estonian concepts must have a Preferred Synonym in Estonian."
	dialect "mvel"
	when
		c : Concept(active)
		d : ArrayList(size > 0 || c.moduleId contains "11000181102") from collect (
			Description(active, conceptId == c.id, typeId == Constants.SYNONYM, languageCode == "et")
		)
		ArrayList(size != 1) from collect (
			Description(active, conceptId == c.id, typeId == Constants.SYNONYM, languageCode == "et", acceptabilityMap["71000181105"] == Constants.ACCEPTABILITY_PREFERRED)
		)
	then
		InvalidContent invalid = new InvalidContent("2643a03e-2a71-454b-b302-1d6d34085e70",
				c, "A concept must have one Preferred Synonym in the EE dialect.", ConceptHelper.isCoreModule(c.moduleId) && !ConceptHelper.isAllComponentsBelongToCoreModule(d));
		invalid.ignorePublishedCheck();
		invalidContent.add(invalid);
end
