import org.ihtsdo.drools.domain.Concept
import org.ihtsdo.drools.domain.Description
import org.ihtsdo.drools.domain.Constants
import java.util.Collection
import java.util.ArrayList
import org.ihtsdo.drools.helper.DescriptionHelper
import org.ihtsdo.drools.response.InvalidContent
import org.ihtsdo.drools.response.Severity

global java.util.List invalidContent

rule "Only one preferred synonym in BE_FR dialect"
	dialect "mvel"
	when
		c : Concept(active)
		ArrayList(size > 0 || c.moduleId == "11000172109") from collect (
			Description(active, conceptId == c.id, typeId == Constants.SYNONYM)
		)
		ArrayList(size > 0, size != 1) from collect (
			Description(active, conceptId == c.id, typeId == Constants.SYNONYM, acceptabilityMap["21000172104"] == Constants.ACCEPTABILITY_PREFERRED)
		)
	then
        InvalidContent invalid = new InvalidContent(c, "A concept should have only one Preferred Synonym in the BE-FR dialect.", Severity.ERROR);
        invalid.ignorePublishedCheck()
        invalidContent.add(invalid);
end
