import org.ihtsdo.drools.domain.Concept
import org.ihtsdo.drools.domain.Description
import org.ihtsdo.drools.domain.Constants
import java.util.Collection
import java.util.ArrayList
import org.ihtsdo.drools.helper.DescriptionHelper
import org.ihtsdo.drools.response.InvalidContent

global java.util.List invalidContent

rule "Preferred synonym per dialect"
    dialect "mvel"
    when
		c : Concept(active)
		ArrayList(size > 0 || c.moduleId contains "1000005") from collect (
			Description(active, conceptId == c.id, typeId == Constants.SYNONYM, languageCode == "dk")
		)
		ArrayList(size != 1) from collect (
			Description(active, conceptId == c.id, typeId == Constants.SYNONYM, languageCode == "dk", acceptabilityMap["554461000005103"] == Constants.ACCEPTABILITY_PREFERRED)
		)
    then
        invalidContent.add(new InvalidContent(c, "The system has detected a contradiction of the following convention: a concept must have one Preferred Synonym in the DK dialect.").ignorePublishedCheck());
end
