import org.ihtsdo.drools.domain.Concept
import org.ihtsdo.drools.domain.Relationship
import org.ihtsdo.drools.helper.RelationshipHelper
import org.ihtsdo.drools.domain.Constants
import org.ihtsdo.drools.response.InvalidContent

global java.util.List invalidContent

rule "Relationship group must have as least two concepts"
    dialect "mvel"
    when
    	c : Concept()
    	r : Relationship(sourceId == c.id && relationshipGroup != 0
    			&& RelationshipHelper.countRelationshipsInGroup(c, relationshipGroup) < 2)
    then
        invalidContent.add(new InvalidContent(r, "The system has detected a contradiction of the following convention: a role group must have at least two relationships."));
end
