import org.ihtsdo.drools.domain.Concept
import org.ihtsdo.drools.domain.Description
import org.ihtsdo.drools.domain.Constants
import org.ihtsdo.drools.helper.DescriptionHelper
import org.ihtsdo.drools.response.InvalidContent
import org.ihtsdo.drools.response.Severity

global java.util.List invalidContent


rule "Terms with matching first word share case significance"
	dialect "mvel"
	when
		c : Concept()
		d : Description(active && caseSignificanceId == Constants.ENTIRE_TERM_CASE_SENSITIVE && !DescriptionHelper.isCaseSignificanceValidBetweenTerms(c, d))
		then
        invalidContent.add(new InvalidContent(d, "The system has detected a contradiction of the following convention: active terms sharing first words should share case sensitivity", Severity.WARNING));
end
