import org.ihtsdo.drools.domain.Concept
import org.ihtsdo.drools.domain.Description
import org.ihtsdo.drools.domain.Constants
import org.ihtsdo.drools.response.InvalidContent
import org.ihtsdo.drools.response.Severity
import org.ihtsdo.drools.helper.DescriptionHelper

global java.util.List invalidContent

rule "FSN and matching PT share case sensitivity"
	dialect "mvel"
	when
		c : Concept()
		dFsn : Description(active == true && typeId == Constants.FSN)
		forall ( dPt : Description( caseSignificanceId != dFsn.caseSignificanceId ) from DescriptionHelper.getActivePreferredTermsForFsn(dFsn, c))
	then
		 invalidContent.add(new InvalidContent(dFsn, "The system has detected a contradiction of the following convention: an active preferred term matching the FSN must have same case significance", Severity.WARNING));
end