import org.ihtsdo.drools.domain.Description
import org.ihtsdo.drools.domain.Constants
import org.ihtsdo.drools.response.InvalidContent
import org.ihtsdo.drools.response.Severity

global java.util.List invalidContent

rule "Term use of quotation marks"
	dialect "mvel"
	when
		d : Description(active == true && (term matches ".*\\’[s]\\s.*" || term matches ".*\\'[s]\\s.*"))
	then
		invalidContent.add(new InvalidContent(d, "An active term should not contain any quotation marks.", Severity.WARNING));
end
