import org.ihtsdo.drools.domain.Concept
import org.ihtsdo.drools.domain.Description
import org.ihtsdo.drools.domain.Constants
import org.ihtsdo.drools.service.DescriptionService
import org.ihtsdo.drools.response.InvalidContent
import org.ihtsdo.drools.response.Severity

global java.util.List invalidContent
global DescriptionService descriptionService


rule "Terms with case significant words are marked case sensitive"
	dialect "mvel"
	when
		c : Concept()
		d : Description(active && d.caseSignificanceId != Constants.ENTIRE_TERM_CASE_SENSITIVE && descriptionService.hasCaseSignificantWord(d.term))
		then
        invalidContent.add(new InvalidContent(d, "The system has detected a contradiction of the following convention: active terms sharing first word with case-sensitive term should have case significance entire term case sensitive", Severity.WARNING));
end
