import org.ihtsdo.drools.domain.Concept
import org.ihtsdo.drools.domain.Description
import org.ihtsdo.drools.domain.Constants
import java.util.Collection
import org.ihtsdo.drools.helper.DescriptionHelper
import org.ihtsdo.drools.response.InvalidContent

global java.util.List invalidContent

rule "A concept must have one Preferred Synonym in GB-English."
	dialect "mvel"
	when
		c : Concept(active && DescriptionHelper.filterByActiveTypeAndDialectPreferred(c, true, Constants.SYNONYM, Constants.GB_EN_LANG_REFSET).size() != 1)
	then
		InvalidContent invalid = new InvalidContent("17ef1693-9e5e-48bd-ae90-c771921bf5bf",
				c, "A concept must have one Preferred Synonym in the GB-EN dialect.");
		invalid.ignorePublishedCheck();
		invalidContent.add(invalid);
end
