import org.ihtsdo.drools.domain.Concept
import org.ihtsdo.drools.domain.Description
import org.ihtsdo.drools.domain.Constants
import org.ihtsdo.drools.response.InvalidContent
import org.ihtsdo.drools.response.Severity
import org.ihtsdo.drools.helper.DescriptionHelper

global java.util.List invalidContent

rule "An active synonym on an active concept should not end with a parenthesis."
	dialect "mvel"
	when
		c : Concept(active)
		d : Description(active && typeId == Constants.SYNONYM && term.endsWith(")") && term not matches ".*\\([^\\(]*")
	then
		invalidContent.add(new InvalidContent("6d2a1740-dc60-45b3-928e-c7fa116f7ca4",
				d, "An active synonym on an active concept should not end with a parenthesis.", Severity.WARNING));
end
