import org.ihtsdo.drools.domain.Concept
import org.ihtsdo.drools.domain.Relationship
import org.ihtsdo.drools.helper.RelationshipHelper
import org.ihtsdo.drools.domain.Constants
import org.ihtsdo.drools.response.InvalidContent
import java.util.ArrayList

global java.util.List invalidContent

rule "Relationship group must have as least two active relationships"
	dialect "mvel"
	when
		c : Concept()
		r : Relationship(active && relationshipGroup != 0 && characteristicTypeId == Constants.STATED_RELATIONSHIP)
		not (exists(Relationship(active == true && id != r.id && relationshipGroup == r.relationshipGroup && characteristicTypeId == Constants.STATED_RELATIONSHIP)))
	then
		invalidContent.add(new InvalidContent(r, "A role group must have at least two active relationships."));
end
