import org.ihtsdo.drools.domain.Description
import org.ihtsdo.drools.domain.Concept
import org.ihtsdo.drools.response.InvalidContent
import org.ihtsdo.drools.response.Severity

global java.util.List invalidContent

rule "No trailing zeros after a decimal point in numerical values with fractions"
	dialect "mvel"
	when
		c : Concept(active)
		d : Description(active && conceptId == c.id && term matches "(.*\\.\\d*[1-9]*0+\\D.*)")
	then
		invalidContent.add(new InvalidContent(d, "The system has detected a contradiction of the following convention: Numeric values should not end with trailing zeros after a decimal point. Exception: A 'trailing zero' may be used only where required to demonstrate the level of precision of the value being reported; it may not be used in medication orders or other medication-related documentation.", Severity.WARNING));
end
