import org.ihtsdo.drools.domain.Concept
import org.ihtsdo.drools.domain.Relationship
import org.ihtsdo.drools.response.InvalidContent
import org.ihtsdo.drools.response.Severity
import org.ihtsdo.drools.domain.Constants

global java.util.List invalidContent

rule "An active rel ationship should have the same Module ID as the concept."
	dialect "mvel"
	when
		c : Concept(active)
		r : Relationship(active && characteristicTypeId == Constants.STATED_RELATIONSHIP && moduleId != c.moduleId)
	then
		InvalidContent invalid = new InvalidContent("cc9f2c3d-f79a-4b15-827e-def8ca2dec25",
				r, "Relationship does not have the same Module ID as the concept.", Severity.WARNING);
		invalid.ignorePublishedCheck();
		invalidContent.add(invalid);
end
