import org.ihtsdo.drools.domain.Description
import org.ihtsdo.drools.response.InvalidContent
import org.ihtsdo.drools.response.Severity

global java.util.List invalidContent

rule "An active term must not contain any non-breaking space characters."
	dialect "mvel"
	when
		d : Description(active && term.contains("\u00A0"))
	then
		invalidContent.add(new InvalidContent("eaf979d2-f6c9-49b9-8e19-d59e40c5eb3a",
				d, "An active term must not contain any non-breaking space characters. " +
				"Please remove and retype each space to fix this."));
end
