import org.ihtsdo.drools.domain.Concept
import org.ihtsdo.drools.domain.Description
import org.ihtsdo.drools.domain.Constants
import org.ihtsdo.drools.response.InvalidContent
import org.ihtsdo.drools.response.Severity
import org.ihtsdo.drools.helper.DescriptionHelper

global java.util.List invalidContent

rule "FSN and matching PT share case sensitivity"
	dialect "mvel"
	when
	    c : Concept()
		d : Description(active == true && typeId == Constants.SYNONYM && DescriptionHelper.isPreferredInAnyDialect(d) && !DescriptionHelper.isPreferredTermCaseSignificanceValid(c, d))
	then
		 invalidContent.add(new InvalidContent(d, "The system has detected a contradiction of the following convention: an active preferred term matching a FSN must have same case significance", Severity.WARNING));
end