import org.ihtsdo.drools.domain.Concept
import org.ihtsdo.drools.domain.Description
import org.ihtsdo.drools.domain.Constants
import org.ihtsdo.drools.response.InvalidContent
import org.ihtsdo.drools.response.Severity
import org.ihtsdo.drools.helper.DescriptionHelper

global java.util.List invalidContent

rule "FSN and matching PT share case sensitivity"
	dialect "mvel"
	when
		c : Concept()
		fsn : Description(active == true && typeId == Constants.FSN && DescriptionHelper.getTag(term) != null
				&& DescriptionHelper.getTag(term).equals(DescriptionHelper.getTag(term).toLowerCase()))
		d : Description(active == true && fsn.languageCode == languageCode && typeId == Constants.SYNONYM && DescriptionHelper.isPreferredInAnyDialect(d) && term == DescriptionHelper.getFsnTerm(fsn.term)
				&& fsn.caseSignificanceId != caseSignificanceId)
	then
		invalidContent.add(new InvalidContent("78f15038-30a0-42ac-9505-cac16e59c28b",
				d, "An active preferred term matching a FSN on an " + (c.active ? "active" : "inactive") +
				" concept must have same case significance.", Severity.WARNING));
end
