import org.ihtsdo.drools.domain.Concept
import org.ihtsdo.drools.domain.Description
import org.ihtsdo.drools.domain.Constants
import java.util.Collection
import org.ihtsdo.drools.helper.DescriptionHelper
import org.ihtsdo.drools.response.InvalidContent

global java.util.List invalidContent

rule "Preferred synonym per dialect"
    dialect "mvel"
    when
    	c : Concept(active && (
    		DescriptionHelper.filterByActiveTypeAndDialectPreferred(c, true, Constants.SYNONYM, Constants.US_EN_LANG_REFSET).size() != 1
    		|| DescriptionHelper.filterByActiveTypeAndDialectPreferred(c, true, Constants.SYNONYM, Constants.GB_EN_LANG_REFSET).size() != 1)
		)
    then
        invalidContent.add(new InvalidContent(c, "The system has detected a contradiction of the following convention: a concept may only have one Preferred Synonym in each dialect.").ignorePublishedCheck());
end
