import org.ihtsdo.drools.domain.Description
import org.ihtsdo.drools.domain.Constants
import org.ihtsdo.drools.response.InvalidContent
import org.ihtsdo.drools.response.Severity

global java.util.List invalidContent

rule "An active term should not contain tabs, newlines, or characters @, $, #, \\."
	dialect "mvel"
	when
		d : Description(active == true && term matches ".*[\\\\\t\r\n@$#].*")
	then
		invalidContent.add(new InvalidContent("fbd4bbb5-3e62-4ccb-824a-e82d9771c0ee",
				d, "An active term should not contain tabs, newlines, or characters @, $, #, \\.", Severity.WARNING));
end

rule "Term contains zero width space characters"
	dialect "mvel"
	when
		d : Description(active && term.contains("\u200B"))
	then
		invalidContent.add(new InvalidContent("09a62d35-87bc-4174-9680-964258bd4062",
				d, "An active term must not contain any \'zero width space\' characters."));
end
