import org.ihtsdo.drools.domain.Description
import org.ihtsdo.drools.domain.Constants
import org.ihtsdo.drools.response.InvalidContent
import org.ihtsdo.drools.response.Severity

global java.util.List invalidContent

rule "New Zealand Extension: Text definitions should be case-sensitive."
	dialect "mvel"
	when
		d : Description(active && textDefinition && caseSignificanceId != Constants.ENTIRE_TERM_CASE_SENSITIVE)
	then
		invalidContent.add(new InvalidContent("402ad3e2-a69f-439b-837a-22ce123b156b",
				d, "Text definitions should be case-sensitive.", Severity.WARNING));
end
