import org.ihtsdo.drools.domain.Concept
import org.ihtsdo.drools.domain.Description
import org.ihtsdo.drools.domain.Constants
import java.util.Collection
import java.util.ArrayList
import org.ihtsdo.drools.helper.DescriptionHelper
import org.ihtsdo.drools.response.InvalidContent

global java.util.List invalidContent

rule "Preferred synonym per dialect"
	dialect "mvel"
	when
	c : Concept(active)
	ArrayList(size > 0 || c.moduleId contains "1000052") from collect (
		Description(active, conceptId == c.id, typeId == Constants.SYNONYM, languageCode == "sv")
	)
	ArrayList(size != 1) from collect (
		Description(active, conceptId == c.id, typeId == Constants.SYNONYM, languageCode == "sv", acceptabilityMap["46011000052107"] == Constants.ACCEPTABILITY_PREFERRED)
	)
	then
		InvalidContent invalid = new InvalidContent("80084f20-f7f4-4d9a-92fd-0819134ab094",
				c, "A concept must have one Preferred Synonym in the SE dialect.");
		invalid.ignorePublishedCheck();
		invalidContent.add(invalid);
end
