import org.ihtsdo.drools.domain.Relationship
import org.ihtsdo.drools.service.ConceptService
import org.ihtsdo.drools.response.InvalidContent

global java.util.List invalidContent
global ConceptService conceptService

rule "Inactive relationship must not be grouped"
    dialect "mvel"
    when
    	r : Relationship(!active && relationshipGroup != 0)
    then
        invalidContent.add(new InvalidContent(r, "The system has detected a contradiction of the following convention: inactive relationships must not not be grouped."));
end
