import org.ihtsdo.drools.domain.Relationship
import org.ihtsdo.drools.service.ConceptService
import org.ihtsdo.drools.response.InvalidContent

global java.util.List invalidContent
global ConceptService conceptService

rule "Concepts must not have inactive relationship types."
	dialect "mvel"
	when
		r : Relationship(active && !conceptService.isActive(typeId))
	then
		invalidContent.add(new InvalidContent("07b567dd-8c13-4ac0-852b-3ddbc969cf8f",
				r, "Concepts must not have inactive relationship types."));
end
