import org.ihtsdo.drools.domain.Concept
import org.ihtsdo.drools.domain.Relationship
import org.ihtsdo.drools.helper.RelationshipHelper
import org.ihtsdo.drools.response.InvalidContent
import org.ihtsdo.drools.domain.Constants

global java.util.List invalidContent

rule "Active Concepts should not have two relationships with the same type, target and group"
	dialect "mvel"
	when
		c : Concept(active)
		r1 : Relationship(sourceId == c.id && characteristicTypeId == Constants.STATED_RELATIONSHIP)
		r2 : Relationship(sourceId == c.id && characteristicTypeId == Constants.STATED_RELATIONSHIP && r1 != this && r1.axiomId == axiomId && typeId == r1.typeId
				&& ((destinationId != null && destinationId == r1.destinationId) || (concreteValue != null && concreteValue == r1.concreteValue))
				&& relationshipGroup == r1.relationshipGroup && (r1.active || r2.active) && (!r1.released || (r1.active && r2.active)))
	then
		invalidContent.add(new InvalidContent("1edb6c09-31ec-4a98-8c98-9409c56e07f1",
				r1, "An active concept must not have two relationships with the same type, target and group. " +
		"The duplicate can be an inactive relationship that should be reactivated, or an unreleased new relationship that should be deleted. " +
		"Please review the following relationship: " + r2.id + "."));
end
