import org.ihtsdo.drools.domain.Concept
import org.ihtsdo.drools.domain.Description
import org.ihtsdo.drools.domain.Constants
import java.util.Collection
import org.ihtsdo.drools.helper.RelationshipHelper
import org.ihtsdo.drools.response.InvalidContent
import org.ihtsdo.drools.response.Severity

global java.util.List invalidContent

rule "Primitive concepts must have one defining relationship"
	dialect "mvel"
	when
		c : Concept(active && definitionStatusId == Constants.DEFINED && relationships.size() == 1)
   	then
		InvalidContent invalid = new InvalidContent(c, c.relationships.size() + ": Concept marked as DEFINED must have more than one definin.");
        invalid.ignorePublishedCheck();
        invalidContent.add(invalid);
end
