import org.ihtsdo.drools.domain.Concept
import org.ihtsdo.drools.domain.Relationship
import org.ihtsdo.drools.domain.Constants
import org.ihtsdo.drools.response.InvalidContent
import org.ihtsdo.drools.response.Severity

import java.util.ArrayList

global java.util.List invalidContent

rule "Primitive concepts must have one defining relationship"
	dialect "mvel"
	when
		c : Concept(active && definitionStatusId == Constants.DEFINED)
		r : ArrayList(size == 1) from collect(Relationship(active, characteristicTypeId == Constants.STATED_RELATIONSHIP))
   	then
		InvalidContent invalid = new InvalidContent(c, "Concept marked as DEFINED must have more than one defining relationship.");
        invalid.ignorePublishedCheck();
        invalidContent.add(invalid);
end
