import org.ihtsdo.drools.domain.Description
import org.ihtsdo.drools.response.InvalidContent

global java.util.List invalidContent

rule "Term prefilled"
    dialect "mvel"
    when
        d : Description(term.toLowerCase matches ".*[ \\(]pre-filled[ \\)].*")
    then
        invalidContent.add(new org.ihtsdo.drools.response.InvalidContent(d, "The system has detected a contradiction of the following convention: FSNs containing the word “pre-filled” must be changed to prefilled."));
end
