import org.ihtsdo.drools.domain.Concept
import org.ihtsdo.drools.domain.Constants
import org.ihtsdo.drools.domain.Relationship
import org.ihtsdo.drools.response.InvalidContent
import org.ihtsdo.drools.service.RelationshipService

global java.util.List invalidContent
global RelationshipService relationshipService

rule "Inactive concepts must not have children."
	dialect "mvel"
	when
		c : Concept(!active && relationshipService.hasActiveInboundStatedRelationship(c.id, Constants.IS_A))
	then
		invalidContent.add(new InvalidContent("c6fec3e3-215a-45b1-9afa-b379ceeaff03",
				c, "Inactive concepts must not have children."));
end
