import org.ihtsdo.drools.domain.Concept
import org.ihtsdo.drools.domain.Description
import org.ihtsdo.drools.domain.Constants
import org.ihtsdo.drools.response.InvalidContent
import org.ihtsdo.drools.response.Severity
import org.ihtsdo.drools.helper.DescriptionHelper
import org.ihtsdo.drools.service.DescriptionService

global java.util.List invalidContent
global DescriptionService descriptionService

rule "An active synonym on an active concept must not have a semantic tag."
	dialect "mvel"
	when
		c : Concept(active)
		d : Description(active && typeId == Constants.SYNONYM && DescriptionHelper.getTag(d.term) != null
				&& descriptionService.isRecognisedSemanticTag(DescriptionHelper.getTag(d.term), d.languageCode))
	then
		invalidContent.add(new InvalidContent("a300355c-6046-4be8-ac09-e5a1cd940ea2",
				d, "An active synonym on an active concept must not have a semantic tag.", Severity.WARNING));
end
