import org.ihtsdo.drools.domain.Concept
import org.ihtsdo.drools.domain.Constants
import org.ihtsdo.drools.domain.Relationship
import org.ihtsdo.drools.response.InvalidContent
import org.ihtsdo.drools.service.RelationshipService

global java.util.List invalidContent
global RelationshipService relationshipService

rule "Inactive concepts must be primitive."
	dialect "mvel"
	when
		c : Concept(!active && definitionStatusId != Constants.PRIMITIVE)
	then
		InvalidContent invalid = new InvalidContent("c635fde4-1019-4d8c-a496-bf2af5208639",
				c, "Inactive concepts must be primitive.");
		invalid.ignorePublishedCheck();
		invalidContent.add(invalid);
end
