import org.ihtsdo.drools.domain.Description
import org.ihtsdo.drools.domain.Concept
import org.ihtsdo.drools.response.InvalidContent
import org.ihtsdo.drools.response.Severity

global java.util.List invalidContent

rule "Numeric values should not end with trailing zeros after a decimal point."
	dialect "mvel"
	when
		c : Concept(active)
		d : Description(active && conceptId == c.id && (term matches "(.*\\.\\d*[1-9]*0\\-.\\d*\\.\\d*.*)" || term matches "(.*\\.\\d*[1-9]\\-.\\d*\\.\\d*[1-9]*0+\\D.*)"))
	then
		invalidContent.add(new InvalidContent("ccbaf61f-8561-49cc-9c07-b57f8ff88047",
				d, "Numeric values should not end with trailing zeros after a decimal point.", Severity.WARNING));
end
