import org.ihtsdo.drools.domain.Concept
import org.ihtsdo.drools.domain.Description
import org.ihtsdo.drools.domain.Constants
import org.ihtsdo.drools.response.InvalidContent
import org.ihtsdo.drools.helper.DescriptionHelper
import org.ihtsdo.drools.domain.Constants
import org.ihtsdo.drools.response.Severity

global java.util.List invalidContent

function int countCharacters(String term, String c) {
	return term.length() - term.replace(c, "").length();
}

rule "Terms contains balanced parentheses"
	dialect "mvel"
	when
		c : Concept(active == true)
		d : Description(conceptId == c.id && active && countCharacters(term, "(") != countCharacters(term, ")"))
	then
		invalidContent.add(new InvalidContent("b5570e20-a7f3-4273-a76d-4b29937c6e76",
				d, "An active term on an active concept should contain balanced parentheses.", Severity.WARNING));
end
