import org.ihtsdo.drools.domain.Relationship
import org.ihtsdo.drools.service.ConceptService
import org.ihtsdo.drools.response.InvalidContent

global java.util.List invalidContent
global ConceptService conceptService

rule "Active relationship must not have inactive destination"
	dialect "mvel"
	when
		r : Relationship(active && destinationId != null && !conceptService.isActive(destinationId))
	then
		invalidContent.add(new InvalidContent("44980955-13e5-4f00-a1cf-968935d20455",
				r, "Concepts must not have relationships to inactive concepts."));
end
