import org.ihtsdo.drools.domain.Concept
import org.ihtsdo.drools.domain.Description
import org.ihtsdo.drools.helper.DescriptionHelper
import org.ihtsdo.drools.response.InvalidContent

global java.util.List invalidContent

rule "Term unique in concept"
    dialect "mvel"
    when
    	c : Concept()
    	d : Description(active && conceptId == c.id && !DescriptionHelper.isUniqueWithinConcept(d, c))
    then
        invalidContent.add(new InvalidContent(d, "The system has detected a contradiction of the following convention: active descriptions must be unique in a concept."));
end
