import org.ihtsdo.drools.domain.Description
import org.ihtsdo.drools.response.InvalidContent
import org.ihtsdo.drools.response.Severity
import org.ihtsdo.drools.domain.Constants

global java.util.List invalidContent


function int countWords(String term) {
	if (term == null || term.isEmpty()) {
		return 0;
	}
	String[] words = term.split("\\s+");
	return words.length;
}

rule "Description normally has less than 35 words"
	dialect "mvel"
	when
		d : Description(active && typeId == Constants.SYNONYM && countWords(term) > 35)
	then
		invalidContent.add(new InvalidContent(d, "An active description normally has less than 35 words.", Severity.WARNING));
end
