import org.ihtsdo.drools.domain.Concept
import org.ihtsdo.drools.domain.Constants
import org.ihtsdo.drools.domain.Description
import org.ihtsdo.drools.helper.DescriptionHelper
import org.ihtsdo.drools.service.DescriptionService
import org.ihtsdo.drools.response.InvalidContent
import org.ihtsdo.drools.response.Severity

global java.util.List invalidContent
global DescriptionService descriptionService

rule "Terms with case sensitive terms are not case insensitive"
    dialect "mvel"
    when
    	c : Concept(active)
    	d : Description(active && descriptionService.getCaseSensitiveWordsErrorMessage(d).length > 0)
        
    then
        invalidContent.add(new InvalidContent(d, "Terms containing case sensitive words should have case significance entire-term-case-sensitive: " + descriptionService.getCaseSensitiveWordsErrorMessage(d), Severity.WARNING))
end