import org.ihtsdo.drools.domain.Concept
import org.ihtsdo.drools.domain.Relationship
import org.ihtsdo.drools.domain.Constants
import org.ihtsdo.drools.service.ConceptService
import org.ihtsdo.drools.response.InvalidContent

global java.util.List invalidContent
global ConceptService conceptService

rule "Inactive concepts must not contain active stated relationships."
	dialect "mvel"
	when
		c : Concept(!active)
		r : Relationship(active && characteristicTypeId == Constants.STATED_RELATIONSHIP)
	then
		invalidContent.add(new InvalidContent("1279cf27-e2dd-42cb-af86-f57addecd32c",
				r, "Inactive concepts must not contain active stated relationships."));
end
