import org.ihtsdo.drools.domain.Description
import org.ihtsdo.drools.domain.Concept
import org.ihtsdo.drools.response.InvalidContent
import org.ihtsdo.drools.response.Severity

global java.util.List invalidContent

rule "Lack of leading zero before a decimal point for decimal values less than one"
	dialect "mvel"
	when
		d : Description(active && ((term matches "^\\.\\d+.*") || (term matches ".*[\\s-_]\\.\\d+.*")))
	then
		invalidContent.add(new InvalidContent("8fa25ba2-b817-426d-ba07-2ff99395f25f",
				d, "Decimal values less than one should include a single leading zero before the decimal point.", Severity.WARNING));
end