import org.ihtsdo.drools.domain.Concept
import org.ihtsdo.drools.domain.Description
import org.ihtsdo.drools.response.InvalidContent

global java.util.List invalidContent

rule "Term prefilled"
	dialect "mvel"
	when
	   c : Concept(active == true)
		d : Description(active == true && term.toLowerCase matches ".*[ \\(]pre-filled[ \\)].*")
	then
		invalidContent.add(new InvalidContent(d, "An FSN containing the word \"pre-filled\" must be changed to prefilled."));
end
