import org.ihtsdo.drools.domain.Concept
import org.ihtsdo.drools.domain.Description
import org.ihtsdo.drools.domain.Constants
import org.ihtsdo.drools.service.DescriptionService
import org.ihtsdo.drools.response.InvalidContent
import org.ihtsdo.drools.response.Severity

global java.util.List invalidContent
global DescriptionService descriptionService

rule "Active FSN should not exist as inactive term on another concept"
    dialect "mvel"
    when
		d : Description(active == true && typeId == Constants.FSN)
		$duplicate : Description(id != d.id && typeId == Constants.FSN) from descriptionService.findInactiveDescriptionByExactTerm(d.term)
    then
        invalidContent.add(new InvalidContent(d, "The system has detected a contradiction of the following convention: FSN exists as inactive on concept " + $duplicate.conceptId + ".", Severity.WARNING));
end
