import org.ihtsdo.drools.domain.Concept
import org.ihtsdo.drools.domain.Description
import org.ihtsdo.drools.domain.Constants
import java.util.Collection
import org.ihtsdo.drools.helper.DescriptionHelper
import org.ihtsdo.drools.response.InvalidContent
import org.ihtsdo.drools.response.Severity

global java.util.List invalidContent

rule "FSN per dialect"
	dialect "mvel"
	when
		c : Concept(active && DescriptionHelper.filterByActiveTypeAndDialectPreferred(c, true, Constants.FSN, Constants.GB_EN_LANG_REFSET).size() != 1)
	then
		invalidContent.add(new InvalidContent(c, "The system has detected a contradiction of the following convention: an active concept should have one active preferred FSN in the GB-EN dialect.").ignorePublishedCheck());
end
