import org.ihtsdo.drools.domain.Concept
import org.ihtsdo.drools.domain.Description
import org.ihtsdo.drools.domain.Constants
import java.util.Collection
import org.ihtsdo.drools.helper.DescriptionHelper
import org.ihtsdo.drools.response.InvalidContent
import org.ihtsdo.drools.response.Severity

global java.util.List invalidContent

rule "An active concept must have one active FSN in the GB-English dialect."
	dialect "mvel"
	when
		c : Concept(active && DescriptionHelper.filterByActiveTypeAndDialectPreferred(c, true, Constants.FSN, Constants.GB_EN_LANG_REFSET).size() != 1)
	then
		InvalidContent invalid = new InvalidContent("a6da818f-8b6f-4a37-a335-3e8180132404",
				c, "An active concept must have one active preferred FSN in the GB-EN dialect.");
		invalid.ignorePublishedCheck();
		invalidContent.add(invalid);
end
