import org.ihtsdo.drools.domain.Concept
import org.ihtsdo.drools.domain.Description
import org.ihtsdo.drools.domain.Constants
import org.ihtsdo.drools.service.DescriptionService
import org.ihtsdo.drools.helper.DescriptionHelper
import org.ihtsdo.drools.helper.RelationshipHelper
import org.ihtsdo.drools.response.InvalidContent
import org.ihtsdo.drools.response.Severity

global java.util.List invalidContent
global DescriptionService descriptionService

// Note - this rule uses international edition language refsets
rule "Semantic Tag of FSN compatible with concept parents"
    dialect "mvel"
    when
        c : Concept(active)
        d : Description(conceptId == c.id
        				&& active
        				&& typeId == Constants.FSN
        				&& !DescriptionHelper.isSemanticTagEquivalentToAnother(
        						term, descriptionService.getFSNs(
        								RelationshipHelper.getActiveStatedParentConceptIds(c),
        								Constants.US_EN_LANG_REFSET,
        								Constants.GB_EN_LANG_REFSET
        								)))
    then
        invalidContent.add(new InvalidContent(d, "The system has detected a contradiction of the following convention: a concept's semantic tags should be compatible with those of the active parents.", Severity.WARNING));
end
