import org.ihtsdo.drools.domain.Concept
import org.ihtsdo.drools.domain.Description
import org.ihtsdo.drools.domain.Constants
import java.util.Collection
import org.ihtsdo.drools.helper.DescriptionHelper
import org.ihtsdo.drools.response.InvalidContent

global java.util.List invalidContent

rule "A concept must have one Preferred Synonym in the US-English dialect."
	dialect "mvel"
	when
		c : Concept(active && DescriptionHelper.filterByActiveTypeAndDialectPreferred(c, true, Constants.SYNONYM, Constants.US_EN_LANG_REFSET).size() != 1)
	then
		InvalidContent invalid = new InvalidContent("9fdf1fa5-e2c5-4a28-a3fa-881728a278b3",
				c, "A concept must have one Preferred Synonym in the US-EN dialect.");
		invalid.ignorePublishedCheck();
		invalidContent.add(invalid);
end
