import org.ihtsdo.drools.domain.Concept
import org.ihtsdo.drools.domain.Constants
import org.ihtsdo.drools.response.InvalidContent
import org.ihtsdo.drools.helper.ConceptHelper
import org.ihtsdo.drools.response.Severity
import org.ihtsdo.drools.service.ConceptService
import java.util.Collection
import java.util.ArrayList

global java.util.List invalidContent
global ConceptService conceptService

rule "Active concept should not belong to more than one top-level hierarchy"
	dialect "mvel"
	when
		c : Concept(active)
		topLevelHierarchies : ArrayList() from collect (
			Concept(id != c.id) from conceptService.findTopLevelHierachiesOfConcept(c)
		)		
	then
		invalidContent.add(new InvalidContent(c, "The system has detected a contradiction of the following convention: Concept should not belong to more than one top-level hierarchy : " + topLevelHierarchies, Severity.ERROR));
end