import org.ihtsdo.drools.domain.Concept
import org.ihtsdo.drools.response.InvalidContent
import org.ihtsdo.drools.service.ConceptService
import org.ihtsdo.drools.response.Severity

global java.util.List invalidContent
global ConceptService conceptService

rule "Active base substance concepts contain some modifications in modelling."
	dialect "mvel"
	when
		c : Concept(active && (id == "387358007" || id == "387327006" || id == "76525000"))
		eval(conceptService.isConceptModellingChanged(c))
	then
		InvalidContent invalid = new InvalidContent("855e8fcf-9c5d-4cbf-99c1-a761df80cbef",
				c, "Active base substance concept contains some modifications in modelling.", Severity.WARNING);
		invalid.ignorePublishedCheck()
		invalidContent.add(invalid);
end
