import org.ihtsdo.drools.domain.Description
import org.ihtsdo.drools.domain.Constants
import org.ihtsdo.drools.response.InvalidContent
import org.ihtsdo.drools.response.Severity

global java.util.List invalidContent

rule "Active FSNs cannot start with open parentheses"
    dialect "mvel"
    when
        d : Description(active == true && typeId == Constants.FSN && term matches "\\(.*")
    then
        invalidContent.add(new InvalidContent(d, "The system has detected a contradiction of the following convention: FSNs must not start with open parentheses."));
end

rule "FSN ends in closing parentheses"
    dialect "mvel"
    when
        d : Description(active == true && typeId == Constants.FSN && term matches ".*[^\\)]")
    then
        invalidContent.add(new InvalidContent(d, "The system has detected a contradiction of the following convention: FSNs must end in closing parentheses."));
end

rule "Active FSN must end with a semantic tag"
    dialect "mvel"
    when
        d : Description(active == true && typeId == Constants.FSN && term not matches ".*\\(.+\\)")
    then
        invalidContent.add(new InvalidContent(d, "The system has detected a contradiction of the following convention: an FSN must end with a semantic tag."));
end

rule "FSN Comma"
    dialect "mvel"
    when
        d : Description(active == true && typeId == Constants.FSN && term matches ".*,.*")
    then
        invalidContent.add(new InvalidContent(d, "The system has detected a contradiction of the following convention: FSNs must not include commas.", Severity.WARNING));
end

rule "FSN space around plus character"
    dialect "mvel"
    when
        d : Description(active == true && typeId == Constants.FSN && (term matches ".*[^ ]\\+.*" || term matches ".*\\+[^ ].*"))
    then
        invalidContent.add(new InvalidContent(d, "The system has detected a contradiction of the following convention: an active FSN containing a + symbol, must include a single space placed at either side of the symbol e.g. Ibuprofen + oxycodone (product)", Severity.WARNING));
end

rule "FSN special characters"
    dialect "mvel"
    when
        d : Description(active == true && typeId == Constants.FSN && term matches ".*[&%$@#].*")
    then
        invalidContent.add(new InvalidContent(d, "The system has detected a contradiction of the following convention: an active FSN must not contain the special characters &, %, $, @ or #.", Severity.WARNING));
end
