import org.ihtsdo.drools.domain.Concept
import org.ihtsdo.drools.domain.Description
import org.ihtsdo.drools.helper.DescriptionHelper
import org.ihtsdo.drools.response.InvalidContent

global java.util.List invalidContent

rule "Term unique in concept"
    dialect "mvel"
    when
        d1 : Description(active)
        d2 : Description(conceptId == d1.conceptId && id != d1.id && term.equals(d1.term) && (typeId.equals(d1.typeId) || active))
    then
        invalidContent.add(new InvalidContent(d1, "The system has detected a contradiction of the following convention: active descriptions must be unique in a concept. " +
         "Two descriptions may have the same term only if they are of different types and one is inactive."));
end
