import org.ihtsdo.drools.domain.Concept
import org.ihtsdo.drools.domain.Description
import org.ihtsdo.drools.domain.Constants
import java.util.Collection
import org.ihtsdo.drools.helper.DescriptionHelper
import org.ihtsdo.drools.response.InvalidContent
import org.ihtsdo.drools.response.Severity

global java.util.List invalidContent

rule "FSN per dialect"
	dialect "mvel"
	when
		c : Concept(active && DescriptionHelper.filterByActiveTypeAndDialectPreferred(c, true, Constants.FSN, Constants.US_EN_LANG_REFSET).size() != 1)
	then
		InvalidContent invalid = new InvalidContent("dbeb9123-f2a0-4aa8-89b2-c49ef5ade27c",
				c, "An active concept should have one active preferred FSN in the US-EN dialect.");
		invalid.ignorePublishedCheck();
		invalidContent.add(invalid);
end
