import org.ihtsdo.drools.domain.Description
import org.ihtsdo.drools.response.InvalidContent
import org.ihtsdo.drools.response.Severity

global java.util.List invalidContent

rule "Description length"
	dialect "mvel"
	when
		d : Description(active && typeId != "900000000000550004" && term.length > 255)
	then
		invalidContent.add(new InvalidContent(d, "An active description must not be longer than 255 characters."));
end

rule "Text Definition length"
	dialect "mvel"
	when
		d : Description(active && typeId == "900000000000550004" && term.length > 4096)
	then
		invalidContent.add(new InvalidContent(d, "An active text definition must not be longer than 4096 characters."));
end
