import org.ihtsdo.drools.domain.Concept
import org.ihtsdo.drools.domain.Description
import org.ihtsdo.drools.domain.Relationship
import org.ihtsdo.drools.domain.Constants
import org.ihtsdo.drools.response.InvalidContent
import org.ihtsdo.drools.response.Severity

import java.util.ArrayList

global java.util.List invalidContent

rule "An axiom marked as fully defined must have at least one attribute relationship."
	dialect "mvel"
	when
		c : Concept(active && definitionStatusId == Constants.DEFINED)
		d : ArrayList(size == 0) from collect(Description(active, moduleId != c.moduleId))
		r : ArrayList(size == 0) from collect(Relationship(active, characteristicTypeId == Constants.STATED_RELATIONSHIP, typeId != Constants.IS_A && !axiomGCI))
	then
		InvalidContent invalid = new InvalidContent("f4c3d61b-c0aa-4f3a-8b2a-1f25414dab24",
				c, "An axiom marked as fully defined must have at least one attribute relationship.");
		invalid.ignorePublishedCheck();
		invalidContent.add(invalid);
end
