import org.ihtsdo.drools.domain.Description
import org.ihtsdo.drools.response.InvalidContent
import org.ihtsdo.drools.response.Severity

global java.util.List invalidContent

rule "Term length"
    dialect "mvel"
    when
        d : Description(term.length > 255)
    then
        invalidContent.add(new InvalidContent(d, "The system has detected a contradiction of the following convention: an active description must not be longer than 255 characters.", Severity.WARNING));
end
