import org.ihtsdo.drools.domain.Concept
import org.ihtsdo.drools.domain.Description
import org.ihtsdo.drools.domain.Constants
import org.ihtsdo.drools.service.DescriptionService
import org.ihtsdo.drools.response.InvalidContent
import org.ihtsdo.drools.response.Severity

global java.util.List invalidContent
global DescriptionService descriptionService


rule "Terms are consistent in en-us and en-gb language refsets"
	dialect "mvel"
	when
		c : Concept(active)
		d : Description(active && descriptionService.getLanguageSpecificErrorMessage(d) != "")
	then
		invalidContent.add(new InvalidContent("e1622b95-aecd-4948-9bcd-81d2e4e3670f",
				d, descriptionService.getLanguageSpecificErrorMessage(d), Severity.WARNING));
end
