import org.ihtsdo.drools.domain.Concept
import org.ihtsdo.drools.domain.Relationship
import org.ihtsdo.drools.response.InvalidContent
import org.ihtsdo.drools.domain.Constants
import org.ihtsdo.drools.response.Severity

global java.util.List invalidContent

rule "Relationship has inappropriate attribute and value"
	dialect "mvel"
	when
		c : Concept(active)
		r : Relationship(active 
						&& characteristicTypeId == Constants.STATED_RELATIONSHIP 
						&& (typeId in ("774158006", "774159003", "774160008", "774161007", "774163005", "774164004", "774167006", "860781008", "860779006") 
							|| (destinationId != null && destinationId in ("774158006", "774159003", "774160008", "774161007", "774163005", "774164004", "774167006"))
							)
						)
	then
		InvalidContent invalid = new InvalidContent("7eb57d03-af1d-4e11-9037-ac3264ca427a",
				r, "Attribute or hierarchy should only be used in national extension model, not in international release.", Severity.WARNING);
		invalid.ignorePublishedCheck();
		invalidContent.add(invalid);
end
