import org.ihtsdo.drools.domain.Description
import org.ihtsdo.drools.domain.Constants
import org.ihtsdo.drools.response.InvalidContent
import org.ihtsdo.drools.response.Severity

global java.util.List invalidContent

rule "Belgian Extension: Text definitions should be case-sensitive."
	dialect "mvel"
	when
		d : Description(active && textDefinition && caseSignificanceId != Constants.ENTIRE_TERM_CASE_SENSITIVE)
	then
		invalidContent.add(new InvalidContent("a7555fdd-d49a-465d-9846-351a1cd92983",
				d, "Text definitions should be case-sensitive.", Severity.WARNING));
end